type typ =
  | TUnit
  | TI32
  | TI8
  | TFun of typ * typ
  | TTup of typ list
  | TVec of typ
  | TVar of tvar
  
and tvar = {
  id : int;
  mutable link : typ option; (* None = unsolved, Some t = solved *)
}

let tvar_counter = ref 0
let uuid_counter = ref 0

let fresh_tvar () : tvar =
  let id = !tvar_counter in
  tvar_counter := id + 1;
  { id; link = None }

let fresh_uuid () : int =
  let id = !uuid_counter in
  uuid_counter := id + 1;
  id

let repr (t : typ) : typ =
  let rec repr_aux t visited =
    match t with
    | TVar {id; link = Some t_linked; _ } -> 
        if List.mem id visited then 
          raise (Errors.TypeError ("[repr] Occurs Check Failed: Recursive types are not allowed. Found tvar: t" ^ string_of_int id ^ "again")) 
        else
          repr_aux t_linked (id :: visited)
    | _ -> t
  in repr_aux t []

let rec cmp_typ (t1 : typ) (t2 : typ) : bool =
  match (repr t1, repr t2) with
  | (TUnit, TUnit) -> true
  | (TI32, TI32) -> true
  | (TI8, TI8) -> true
  | (TFun (t1a, t1b), TFun (t2a, t2b)) -> cmp_typ t1a t2a && cmp_typ t1b t2b
  | (TTup ts1, TTup ts2) -> List.length ts1 = List.length ts2 && List.for_all2 cmp_typ ts1 ts2
  | (TVec t1_inner, TVec t2_inner) -> cmp_typ t1_inner t2_inner
  | (TVar v1, TVar v2) -> v1.id = v2.id
  | _ -> false

type uuid = int 

type schema = Forall of int list * typ (*to be honest the Forall is just annoying*)

type typenv = (string * (schema * uuid)) list

type constraints = (typ * typ) list

let gen_builtins () : typenv =
  let builtins = [
    ("readi8", (Forall ([], TFun (TUnit, TI8)), fresh_uuid ()));
    ("writei8", (Forall ([], TFun (TI8, TUnit)), fresh_uuid ()));
    ("flush", (Forall ([], TFun (TUnit, TUnit)), fresh_uuid ()));
    ("i32_to_i8", (Forall ([], TFun (TI32, TI8)), fresh_uuid ()));
    ("i8_to_i32", (Forall ([], TFun (TI8, TI32)), fresh_uuid ()));
  ] in
  builtins

let builtin_names : string list = List.map (fun (name, _) -> name) (gen_builtins ())

type bopi32 = 
    | Eqi32 | Neqi32 | Lti32 | Gti32 | LtEqi32 | GtEqi32
    | ULti32 | UGti32 | ULtEqi32 | UGtEqi32
    | Muli32 | Subi32 | Addi32 | Divi32 | Modi32
    | UDivi32 | UModi32
    | Andi32 | Ori32 | Xori32
    | Shli32 | Shri32 | UShri32

type uopi32 = 
    | Negi32 | Noti32

type bopi8 = 
    | Eqi8 | Neqi8 | Lti8 | Gti8 | LtEqi8 | GtEqi8
    | Addi8 | Subi8
    | Andi8 | Ori8 | Xori8

type uopi8 = 
    | Negi8 | Noti8
            

type lexp =                                             (*expression*)
    | Var of string                                     (*x*)
    | Lam of string * typ option * typ option * lexp    (*\ x : inTyp => outTyp .y*)
    | LamUnit of lexp                                   (*\() e*)
    | App of lexp * lexp                                (*x y*)
    | Seq of lexp * lexp                                (*x; y*)
    | If of lexp * lexp * lexp                          (*if c then t else e*)
    | Letin of string * lexp * lexp                     (*let x = e in b*)
    | Letrecin of string * lexp * lexp                  (*letrec x = e in b*)
    | LetinTuple of string list * lexp * lexp           (*let (x1, x2, ..., xn) = e in b*)
    | Tuple of lexp list                                (*(e1, e2, ..., en)*)
    | I32Lit of int                                     (*i32*)
    | I8Lit of char                                     (*i8*)
    | UnitLit                                           (*()*)
    | UopI32 of uopi32 * lexp                           (*uop x*)
    | UopI8 of uopi8 * lexp                             (*uop x*)
    | BopI32 of bopi32 * lexp * lexp                    (*x bop y*)
    | BopI8 of bopi8 * lexp * lexp                      (*x bop y*)
    | VecLit of lexp list                               (*vec[e1, e2, ..., en]*)
    | Vecmk of lexp * (lexp list)                       (*vecmk[defval, size list]*)
    | Veclen of lexp                                    (*veclen[v]*)
    | Vecget of lexp * (lexp list)                      (*vecget[v, idx list]*)
    | Vecset of lexp * lexp * (lexp list)               (*vecset[v, val, idx list]*)
    | Vecresz of lexp * lexp * lexp * lexp              (*vecresz[v, defval, newstart, newend]*)

type stmt = 
    | IncludeGlobal of string
    | IncludeRelative of string
    | Let of string * lexp 
    | Letrec of (string * lexp) list

(*
  The Abstract Syntax Tree (ast) is:
    - generated by the parser
    - ,transformed/used by include and reccheck 
    - and consumed by the type checker
*)
type ast = stmt list

type tlexp =                                                      (*typed expression*)
    | VarT of (string ref) * (uuid ref) * typ                     (*x : T*)
    | LamT of string * uuid * tlexp * typ                         (*\ x : inTyp => outTyp .y : T*)
    | LamUnitT of tlexp * typ                                     (*\() e : T*)
    | AppT of tlexp * tlexp * typ                                 (*x y : T*)
    | SeqT of tlexp * tlexp * typ                                 (*x; y : T*)
    | IfT of tlexp * tlexp * tlexp * typ                          (*if c then t else e : T*)
    | LetinT of string * uuid * tlexp * tlexp * typ               (*let x = e in b : T*)
    | LetrecinT of string * uuid * tlexp * tlexp * typ            (*letrec x = e in b : T*)
    | LetinTupleT of ((string * uuid) option) list * tlexp * tlexp * typ   (*let (x1, x2, ..., xn) = e in b : T*)
    | TupleT of tlexp list * typ                                  (*(e1, e2, ..., en) : T*)
    | I32LitT of int * typ                                        (*i32 : T*)
    | I8LitT of char * typ                                        (*i8 : T*)
    | UnitLitT of typ                                             (*() : T*)
    | UopI32T of uopi32 * tlexp * typ                             (*uop x : T*)
    | UopI8T of uopi8 * tlexp * typ                               (*uop x : T*)
    | BopI32T of bopi32 * tlexp * tlexp * typ                     (*x bop y : T*)
    | BopI8T of bopi8 * tlexp * tlexp * typ                       (*x bop y : T*)
    | VecLitT of tlexp list * typ                                 (*vec[e1, e2, ..., en] : T*)
    | VecmkT of tlexp * (tlexp list) * typ                        (*vecmk[defval, size list] : T*)
    | VeclenT of tlexp * typ                                      (*veclen[v] : T*)
    | VecgetT of tlexp * (tlexp list) * typ                       (*vecget[v, idx list] : T*)
    | VecsetT of tlexp * tlexp * (tlexp list) * typ               (*vecset[v, val, idx list] : T*)
    | VecreszT of tlexp * tlexp *  tlexp * tlexp * typ            (*vecresz[v, defval, newstart, newend] : T*)

type polytletbnd = string * uuid * (uuid list) * tlexp

(*
  The Polymorpic Typed Abstract Synatx Tree (polytast) is:
    - generated by the typechecker
    - and consumed by the monomorphizer
*)

type polytast = polytletbnd list


type monotletbnd = string * uuid * tlexp

(*
  The Monomorphic Typed Abstract Syntax Tree (monotast) is:
    - generated by the monomorphizer
    - and consumed by the MIR lowering
*)

type monotast = monotletbnd list


(*Helpers*)
let tlexp_get_type (e : tlexp) : typ =
  match e with
  | VarT (_, _, t) -> t
  | LamT (_, _, _, t) -> t
  | LamUnitT (_, t) -> t
  | AppT (_, _, t) -> t
  | SeqT (_, _, t) -> t
  | IfT (_, _, _, t) -> t
  | LetinT (_, _, _, _, t) -> t
  | LetrecinT (_, _, _, _, t) -> t
  | LetinTupleT (_, _, _, t) -> t
  | TupleT (_, t) -> t
  | I32LitT (_, t) -> t
  | I8LitT (_, t) -> t
  | UnitLitT t -> t
  | UopI32T (_, _, t) -> t
  | UopI8T (_, _, t) -> t
  | BopI32T (_, _, _, t) -> t
  | BopI8T (_, _, _, t) -> t
  | VecLitT (_, t) -> t
  | VecmkT (_, _, t) -> t
  | VeclenT (_, t) -> t
  | VecgetT (_, _, t) -> t
  | VecsetT (_, _, _, t) -> t
  | VecreszT (_, _, _, _, t) -> t

let schema_of_typ (t : typ) : schema = Forall ([], t)

let typ_of_schema (s : schema) : typ =
  match s with
  | Forall (_, t) -> t

let genvars_of_schema (s : schema) : int list =
  match s with
  | Forall (vars, _) -> vars